source "./utils.tcl"

set adjectives {
    "危ない" "あぶない - dangerous"
    "赤い" "あかい - red, crimson, scarlet​"
    "明るい" "あかるい - bright, light"
    "甘い" "あまい - sweet, sweet-tasting, sugary, naive, indulgent"
    "青い" "あおい - blue, azure"
    "新しい" "あたらしい - new, novel, fresh, recent, latest"
    "暖かい" "あたたかい - warm"
    "厚い" "あつい - thick"
    "暑い" "あつい - hot, sultry"
    "熱い" "あつい - hot"
    "便利" "べんり - convenient, handy, useful"
    "小さい" "ちいさい - small, little, tiny"
    "近い" "ちかい - near, close"
    "大丈夫" "だいじょうぶ - OK, okay, alright, problem free"
    "大好き" "だいすき - love, like, like very much"
    "古い" "ふるい - old (not used for people)"
    "太い" "ふとい - fat, thick"
    "元気" "げんき - lively, full of spirit, energetic, healthy"
    "早い" "はやい - fast, early"
    "速い" "はやい - fast, quick, hasty, brisk"
    "下手" "へた - unskillful, poor, awkward"
    "低い" "ひくい - short,low"
    "暇" "ひま - free time"
    "広い" "ひろい - spacious, vast, wide"
    "本当" "ほんとう - truth, reality, actuality, fact"
    "欲しい" "ほしい - want"
    "細い" "ほそい - thin, slender"
    "色々" "いろいろ - various"
    "忙しい" "いそがしい - busy"
    "痛い" "itai - painful, sore"
    "嫌" "iya - unpleasant"
    "丈夫" "joubu - strong, durable"
    "上手" "jouzu - skillful, skilled, proficient, good (at)"
    "辛い" "karai - spicy"
    "軽い" "karui - light"
    "可愛い" "kawaii - cute"
    "結構" "kekkou - splendid, enough"
    "黄色い" "kiiroi - yellow"
    "嫌い" "kirai - hate"
    "綺麗" "kirei - pretty, lovely, beautiful"
    "汚い" "kitanai - dirty"
    "暗い" "kurai - dark, gloomy, murky"
    "黒い" "kuroi - black"
    "丸い" "marui - round,circular"
    "真っ直ぐ" "massugu - straight ahead,direct"
    "不味い" "mazui - unpleasant"
    "短い" "mijikai - short"
    "難しい" "muzukashii - difficult"
    "長い" "nagai - long (distance), long (time), lengthy."
    "賑やか" "nigiyaka - bustling,busy"
    "温い" "nurui - luke warm"
    "美味しい" "oishii - delicious"
    "重い" "omoi - heavy"
    "面白い" "omoshiroi - interesting"
    "多い" "ooi - many, numerous, a lot, large quantity, frequent"
    "大きい" "ookii - big, large, great, important"
    "遅い" "osoi - slow, time-consuming, late"
    "立派" "rippa - splendid"
    "寒い" "samui - cold"
    "狭い" "semai - narrow"
    "白い" "shiroi - white"
    "静か" "shizuka - quiet"
    "好き" "suki - like"
    "少ない" "sukunai - few, a little, scarce, insufficient, seldom"
    "涼しい" "suzushii - refreshing, cool"
    "多分" "tabun - perhaps, probably"
    "大変" "taihen - very, greatly, terribly, serious, difficult"
    "大切" "taisetsu - important, necessary, indispensable, beloved"
    "高い" "takai - high, tall, expensive, above average"
    "沢山" "takusan - many"
    "楽しい" "tanoshii - enjoyable, fun"
    "遠い" "tooi - far"
    "詰まらない" "tsumaranai - boring"
    "冷たい" "tsumetai - cold to the touch"
    "強い" "tsuyoi - powerful"
    "煩い" "urusai - noisy, annoying"
    "薄い" "usui - thin, weak"
    "若い" "wakai - young"
    "悪い" "warui - bad, poor, undesirable"
    "易しい" "yasashii - easy, simple"
    "安い" "yasui - cheap, inexpensive"
    "良い" "yoi/ii - good"
    "弱い" "yowai - weak"
    "有名" "yuumei - famous"
}

proc runAdjectiveQuiz {} {
    global adjectives

    set adjective [getRandomElement [dict keys $adjectives]]
    set correctAnswer [dict get $adjectives $adjective]

    puts "--------------------------------------------------------"
    puts "Assess correctly the adjective's meaning : $adjective"

    flush stdout
    set userAnswer [gets stdin]

    puts "The full answer is $correctAnswer"
}