source "./utils.tcl"

set words {
    "ありがとう" "Thank you"
    "おはよう" "Good morning"
    "こんにちは" "Hello / Good afternoon"
    "こんばんは" "Good evening"
    "さようなら" "Goodbye"
    "はい" "Yes"
    "いいえ" "No"
    "すみません" "Excuse me / I'm sorry"
    "ごめんなさい" "I'm sorry"
    "いただきます" "Thank you for the meal (before eating)"
    "お疲れ様" "Thank you for your hard work"
    "お願いします" "Please"
    "どうぞ" "Here you go / Please"
    "お元気ですか" "How are you?"
    "はじめまして" "Nice to meet you"
    "お名前は何ですか" "What is your name?"
    "わかりました" "I understand"
    "分かりません" "I don't understand"
    "すごい" "Amazing"
    "だめ" "No good / Not allowed"
    "大丈夫" "Okay / All right"
    "ありがとうございます" "Thank you very much"
    "どういたしまして" "You're welcome"
    "失礼しました" "I apologize / Excuse me"
    "お先に失礼します" "I'll excuse myself first"
    "行ってきます" "I'm going (and will come back)"
    "ただいま" "I'm back"
    "お疲れ様でした" "Thank you for your hard work (after work)"
    "おめでとう" "Congratulations"
    "かわいい" "Cute"
    "かっこいい" "Cool"
    "好き" "Like / Love"
    "嫌い" "Dislike / Hate"
    "大好き" "I love you"
    "分かる" "To understand"
    "知っています" "I know"
    "知りません" "I don't know"
    "言ってください" "Please say it"
    "教えてください" "Please teach me"
    "ありがとう" "Thank you"
    "ごめん" "Sorry"
    "すごい" "Amazing"
    "楽しい" "Fun"
    "美味しい" "Delicious"
    "綺麗" "Beautiful / Clean"
    "忙しい" "Busy"
    "暇" "Free / Not busy"
    "早い" "Early"
    "遅い" "Late"
    "大きい" "Big"
    "小さい" "Small"
    "新しい" "New"
    "古い" "Old"
    "高い" "High / Expensive"
    "安い" "Low / Cheap"
    "広い" "Wide"
    "狭い" "Narrow"
    "近い" "Near"
    "遠い" "Far"
    "健康" "Health"
    "病気" "Sickness"
    "医者" "Doctor"
    "病院" "Hospital"
    "薬" "Medicine"
    "笑顔" "Smile"
    "涙" "Tears"
    "心" "Heart"
    "夢" "Dream"
}

proc runVocabularyQuiz {} {
    global words

    set word [getRandomElement [dict keys $words]]
    set correctAnswer [dict get $words $word]

    puts "--------------------------------------------------------"
    puts "Assess correctly this word's meaning : $word"

    flush stdout
    set userAnswer [gets stdin]

    puts "The full answer is $correctAnswer"
}